// @generated by protoc-gen-connect-web v0.6.0 with parameter "target=ts"
// @generated from file proto/greet/greet.proto (package greet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GreetRequest, GreetResponse } from "./greet_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service greet.GreetService
 */
export const GreetService = {
  typeName: "greet.GreetService",
  methods: {
    /**
     * @generated from rpc greet.GreetService.Greet
     */
    greet: {
      name: "Greet",
      I: GreetRequest,
      O: GreetResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

